ALTER TABLE "RUOYI"."SYS_USER" ADD "TENANT_ID" VARCHAR(20 CHAR) DEFAULT '000000' NOT NULL;
/
ALTER TABLE "RUOYI"."SYS_USER" ADD "PWD_UPDATE_DATE" TIMESTAMP(0);
/
ALTER TABLE "RUOYI"."SYS_USER" ADD "TRY_COUNT" INT DEFAULT 0 NOT NULL;
/
exit
/