SET SCHEMA "RUOYI";
/
UPDATE "RUOYI"."SYS_USER" SET "PASSWORD"='$2a$10$7enLynIxoPtVkY40vnf/Ceyi/C9oLKY7eAF66lFN9P9MF9nQHO.Ny', "TRY_COUNT"=0 WHERE "USER_NAME"='admin';
/
SELECT "USER_NAME", "PASSWORD", "STATUS", "DEL_FLAG", "TRY_COUNT" FROM "RUOYI"."SYS_USER" WHERE "USER_NAME"='admin';
/
exit
/